"""
Main Execution Script for NicotineWire AI Ingestion & Publishing Pipeline.
Execute this script to ingest, generate, and publish B2B intelligence stories.
"""

import os
import sys
import time

# Ensure current folder is on python path
sys.path.insert(0, os.path.dirname(__file__))

from news_ingest import ingest_all_sources, fetch_dynamic_ticker_data
from crew_writer import run_crew_pipeline
from publisher import publish_articles_to_index, update_index_ticker


def run_single_iteration():
    print("\n==================================================")
    print("  NICOTINEWIRE AI INGESTION & CREW PUBLISHING     ")
    print("==================================================")
    
    # Step 0: Dynamic Market Ticker Update
    ticker_data = fetch_dynamic_ticker_data()
    update_index_ticker(ticker_data)
    
    # Step 1: Ingest
    raw_items = ingest_all_sources()
    if not raw_items:
        print("[Error] No items ingested.")
        return
        
    # Step 2: Write via CrewAI Agents (IBM Granite 4.1 8B via OpenRouter)
    articles = run_crew_pipeline(raw_items)
    if not articles:
        print("[Error] No articles generated by agents.")
        return
        
    # Step 3: Publish to index.html
    success = publish_articles_to_index(articles)
    if success:
        print("[Pipeline Success] Published stories to nicotinewire/index.html!")


def main():
    interval_seconds = 3600  # Default 1 hour
    if "--loop" in sys.argv:
        print(f"[Daemon Mode] Running autonomous CrewAI pipeline every {interval_seconds} seconds...")
        while True:
            try:
                run_single_iteration()
            except Exception as e:
                print(f"[Daemon Error] Iteration failed: {e}")
            print(f"[Daemon Sleeping] Next run in {interval_seconds // 60} minutes...")
            time.sleep(interval_seconds)
    else:
        run_single_iteration()


if __name__ == "__main__":
    main()
